// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['app', 'text!apps/users/bulkadd/templates/bulkadd.html'], function(App, userAddTpl) {
    return App.module("Users.BulkAdd.Views", function(Views, App) {
      return Views.UsersBulkView = (function(_super) {
        __extends(UsersBulkView, _super);

        function UsersBulkView() {
          return UsersBulkView.__super__.constructor.apply(this, arguments);
        }

        UsersBulkView.prototype.template = userAddTpl;

        UsersBulkView.prototype.className = '';

        return UsersBulkView;

      })(Marionette.ItemView);
    });
  });

}).call(this);
