// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['extm'], function(Extm) {
  var MainController, facing, facingnames, mainView, view, viewnames;
  view = [];
  facing = [];
  facingnames = [];
  viewnames = [];
  MainController = (function(_super) {
    __extends(MainController, _super);

    function MainController() {
      this._getView = __bind(this._getView, this);
      this.showRegionViews = __bind(this.showRegionViews, this);
      return MainController.__super__.constructor.apply(this, arguments);
    }

    MainController.prototype.initialize = function() {
      var layout;
      this.layout = layout = this._getView();
      App.layout = this.layout;
      this.listenTo(layout, 'show', this.showRegionViews);
      return this.show(layout);
    };

    MainController.prototype.showRegionViews = function() {
      msgbus.showApp('booking:header').insideRegion(App.headerRegion).withOptions();
      return msgbus.showApp('booking:screen:one').insideRegion(this.layout.screenOneRegion).withOptions();
    };

    MainController.prototype._getView = function() {
      return new mainView({
        templateHelpers: {
          SITEURL: SITEURL,
          VIEWS: VIEWS,
          FACINGS: FACINGS
        }
      });
    };

    return MainController;

  })(Extm.RegionController);
  mainView = (function(_super) {
    __extends(mainView, _super);

    function mainView() {
      return mainView.__super__.constructor.apply(this, arguments);
    }

    mainView.prototype.template = '<div class="container "> <div class="page-container"> <h3 class="session text-center"></h3> <div class="accordion "> <h3 class="light text-center m-t-0 step1">4 STEPS TO BUYING YOUR APARTMENT</h3> <h4 class="text-center introTxt">Complete your booking securely through our payment gateway.</h4> <div class="accordion-group one open viewed"> <div class="acc-title"> <h4>1. Sign In</h4> </div> <div class="acc-body"> <div id="screen-one-region" class="section"> </div> </div> </div> <div class="accordion-group two"> <div class="acc-title"> <h4>2. Review Details</h4> </div> <div class="acc-body"> <div id="screen-two-region" > </div> </div> </div> <div class="accordion-group three"> <div class="acc-title"> <h4>3. Enter Personal Details</h4> </div> <div class="acc-body"> <div id="screen-three-region" > </div> </div> </div> <div class="accordion-group four"> <div class="acc-title"> <h4>4. Payment</h4> </div> <div class="acc-body"> <div id="screen-four-region" > </div> </div> </div> </div> </div> </div>';

    mainView.prototype.regions = {
      screenOneRegion: '#screen-one-region',
      screenTwoRegion: '#screen-two-region',
      screenThreeRegion: '#screen-three-region',
      screenFourRegion: '#screen-four-region'
    };

    return mainView;

  })(Marionette.LayoutView);
  return msgbus.registerController('booking:main:app', MainController);
});
