// Generated by CoffeeScript 1.7.1
define('plugin-loader', ['handlebars', 'parsleyjs', 'jqueryui', 'autoNumeric'], function() {});

define('apps-loader', ['src/apps/footer/footer-controller', 'src/apps/booking/header/header-controller', 'src/apps/booking/booking-main/main-layout', 'src/apps/booking/screen-one/screen-one-controller', 'src/apps/booking/screen-two/screen-two-controller', 'src/apps/booking/screen-three/screen-three-controller'], function() {});

require(['plugin-loader', 'extm', 'src/classes/ap-store', 'src/apps/router', 'apps-loader'], function(plugins, Extm) {
  var staticApps;
  window.App = new Extm.Application;
  App.layout = "";
  App.addRegions({
    headerRegion: '#header-region',
    footerRegion: '#footer-region',
    filterRegion: '#filter-region',
    mainRegion: '#main-region'
  });
  staticApps = [];
  if (window.location.hash === '') {
    staticApps.push(['booking:main:app', App.mainRegion]);
  }
  App.addStaticApps(staticApps);
  return App.start();
});
